// Generated by CoffeeScript 1.9.1
(function() {
  var NodeObjectStream, fileStream, fs, nos;

  NodeObjectStream = require('./node-object-stream');

  fs = require('fs');

  fileStream = fs.createReadStream('./file');

  nos = fileStream.pipe(new NodeObjectStream);

  nos.on('object', function(str) {
    return console.log(JSON.stringify(str));
  });

  nos.on('end', function() {
    return console.log("asdf");
  });

}).call(this);
